modLoader="javafml"

loaderVersion="[31,)"

#issueTrackerURL="https://github.com/Coliwogg/Ores-and-Metals/issues"

[[mods]]

modId="oresandmetals"

version="1.0.1"

displayName="Ores and Metals"

#updateJSONURL=""

displayURL="https://www.curseforge.com/minecraft/mc-mods/ores-and-metals"

logoFile="logo.png"

credits="Thanks to YOU for downloading this mod!"

authors="Coliwogg"

description='''This mod adds different kinds of ores and metals inspired by the game "RuneScape" to Minecraft.'''



[[dependencies.oresandmetals]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oresandmetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
