modLoader="javafml"

loaderVersion="[37,)"

license="All rights reserved"

issueTrackerURL="https://github.com/Coliwogg/Ores-and-Metals/issues"

[[mods]]

modId="oresandmetals"

version="1.17.1-1.2.0"

displayName="Ores and Metals Mod"

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/ores-and-metals"

logoFile="logo.png"

credits="Thank you for downloading this mod!"

authors="Coliwogg"

description='''This mod adds different kinds of ores, metals, tools, and armor inspired by the game RuneScape to Minecraft.'''

[[dependencies.oresandmetals]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oresandmetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
