name: build
on: [pull_request, push]
  
jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: 7.2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        uses: gradle/gradle-build-action@v2.0.1
        with:
          gradle-version: 7.2
      - name: Build Forge Project
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd forge
          chmod +x ./gradlew
          ./gradlew build
      - name: Build Fabric Project
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd fabric
          chmod +x ./gradlew
          ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          gradle-version: 7.2
          name: Artifacts
          path: build/libs/
